### PR TITLE
Allow graphql 16 as peer dependency

### PR DESCRIPTION
**Pull request by bohdanbirdie**
`@apollo/client: ^3.6.8` uses `graphql: 16.5.0`, making this package unusable because NPM won't allow installing it.

Ref: https://github.com/apollographql/apollo-client/blob/main/package.json#L128

### CODE REVIEW

**Comment by bohdanbirdie** [comment]
Hey @amannn 
Would it be possible to get this merged?

**Comment by amannn** [comment]
Hey @bohdanbirdie and thank you for your PR!

Sure, sounds good! Would you mind bumping the React peer dependency to 18 while you're at it?

**Comment by bohdanbirdie** [comment]
sure, @amannn 
done

**Comment by bohdanbirdie** [comment]
@amannn would you mind delivering a new release version to npm?

**Comment by amannn** [comment]
It should already be released, do you have an issue with the new version?

**Comment by bohdanbirdie** [comment]
My bad @amannn, I was only looking into the GH tags, didn't check the NPM page
All good

**Pull request merged**
